class Flag:
    ALLOW_FULL_ROTATION = 1 << 0
    STREAM_LOW_PRIORITY = 1 << 1
    DISABLE_EMBEDDED_COLLISION = 1 << 2
    LOD_IN_PARENT = 1 << 3
    LOD_ADOPT_ME = 1 << 4
    STATIC_ENTITY = 1 << 5
    LIGHTS_CAST_STATIC_SHADOWS = 1 << 19
    LIGHTS_CAST_DYNAMIC_SHADOWS = 1 << 20
    UNKNOWN_21 = 1 << 21
    DONT_RENDER_IN_REFLECTIONS = 1 << 24
    ONLY_RENDER_IN_REFLECTIONS = 1 << 25
    DONT_RENDER_IN_WATER_REFLECTIONS = 1 << 26
    ONLY_RENDER_IN_WATER_REFLECTIONS = 1 << 27

    LIGHTS_CAST_SHADOWS = LIGHTS_CAST_STATIC_SHADOWS | LIGHTS_CAST_DYNAMIC_SHADOWS

    FLAGS_LOD = LIGHTS_CAST_SHADOWS
    FLAGS_SLOD1 = FLAGS_SLOD2 = LIGHTS_CAST_SHADOWS
    FLAGS_SLOD3 = FLAGS_SLOD4 = LIGHTS_CAST_SHADOWS

    # TODO do not exclude STATIC_ENTITY?
    FLAGS_HD_EXCLUDE_DEFAULT = STATIC_ENTITY | UNKNOWN_21
    FLAGS_HD_DEFAULT = LIGHTS_CAST_SHADOWS | LOD_IN_PARENT

    # TODO do not exclude STATIC_ENTITY?
    FLAGS_ORPHANHD_EXCLUDE_DEFAULT = STATIC_ENTITY | LOD_IN_PARENT | UNKNOWN_21
    FLAGS_ORPHANHD_DEFAULT = LIGHTS_CAST_SHADOWS | ALLOW_FULL_ROTATION | STREAM_LOW_PRIORITY
