class LodLevel:
    ORPHAN_HD = "LODTYPES_DEPTH_ORPHANHD"
    HD = "LODTYPES_DEPTH_HD"
    LOD = "LODTYPES_DEPTH_LOD"
    SLOD1 = "LODTYPES_DEPTH_SLOD1"
    SLOD2 = "LODTYPES_DEPTH_SLOD2"
    SLOD3 = "LODTYPES_DEPTH_SLOD3"
    SLOD4 = "LODTYPES_DEPTH_SLOD4"